attendance/lib/loginPage/login_page_viewmodel.dart

#2 took data of users

---

attendance/lib/BackEnd/user.dart
attendance/pubspec.yaml
attendance/test/userdata_test.dart

track issue here:
https://github.com/ammaratef45/Attendance/issues/27

user class unit tests

---

README.md

track issue here:
https://github.com/ammaratef45/Attendance/issues/22

Performance tools section Added to README.md

---

attendance/lib/BackEnd/user.dart
attendance/lib/ProfilePage/profile_page_view.dart
attendance/test/userdata_test.dart

track issue here:
https://github.com/ammaratef45/Attendance/issues/31

User class validation methods 

---

attendance/lib/BackEnd/user.dart
attendance/test/userdata_test.dart

Track Singleton issue here: 
https://github.com/ammaratef45/Attendance/issues/32
&
Track the commented tests issue here:
https://github.com/ammaratef45/Attendance/issues/30

Fixed user Singleton  

---

attendance/lib/ProfilePage/profile_page.dart
attendance/lib/ProfilePage/profile_page_view.dart
attendance/lib/ProfilePage/profile_page_viewmodel.dart

Cleaned Profile Module from Dart warnings

---

attendance/lib/ProfilePage/profile_page_view.dart
attendance/lib/ProfilePage/profile_page_viewmodel.dart
attendance/lib/backend/user.dart

Added User data TextField validators

---

attendance/lib/offline_page/offline_page_viewmodel.dart

PR for #46 
Removed the useless method.

#46 removed isscanned method

---

attendance/lib/homePage/home_page_view.dart
attendance/lib/homePage/home_page_viewmodel.dart

Replaced scan tab with FAB

---

attendance/lib/dialogs.dart
attendance/lib/homePage/home_page.dart
attendance/lib/homePage/home_page_view.dart
attendance/lib/homePage/home_page_viewmodel.dart
attendance/test/dialogs_test.dart

PR for #64 showing a dialogue for results scan

#64 show dialog for the scan result

---

attendance/lib/backend/api.dart
attendance/lib/backend/session.dart
attendance/lib/homePage/home_page_viewmodel.dart
attendance/test/api_test.dart

#48 added api method and tests

---

attendance/lib/AttendanceDatailsPage/attendance_details_page_viewmodel.dart
attendance/lib/backend/attendance.dart
attendance/lib/homePage/home_page_view.dart
attendance/lib/homePage/home_page_viewmodel.dart

#76 renamed the model attendance

---

attendance/lib/backend/scan.dart
attendance/lib/db/database.dart
attendance/lib/offline_page/offline_page_viewmodel.dart

#74 renamed the file

---

attendance/lib/backend/scan_model.dart
attendance/lib/db/database.dart
attendance/lib/offline_page/offline_page_viewmodel.dart

#75 refactored all vars of scan model

---

attendance/lib/AttendanceDatailsPage/attendance_details_page_viewmodel.dart
attendance/lib/backend/attendance.dart
attendance/lib/homePage/home_page_view.dart
attendance/lib/homePage/home_page_viewmodel.dart

#77 refactored attendance model

---

attendance/lib/AttendanceDatailsPage/attendance_details_page_viewmodel.dart
attendance/lib/backend/attendance.dart

#78 refactored the attendance model

---

attendance/lib/AttendanceDatailsPage/attendance_details_page.dart
attendance/lib/AttendanceDatailsPage/attendance_details_page_view.dart
attendance/lib/AttendanceDatailsPage/attendance_details_page_viewmodel.dart
attendance/lib/backend/attendance.dart
attendance/lib/homePage/home_page_viewmodel.dart
attendance/lib/main.dart

 #79 refactored the code to match the required in issue

---

attendance/lib/AttendanceDatailsPage/attendance_details_page.dart
attendance/lib/AttendanceDatailsPage/attendance_details_page_viewmodel.dart
attendance/lib/backend/scan.dart
attendance/lib/homePage/home_page_viewmodel.dart
attendance/lib/loginPage/login_page.dart
attendance/lib/loginPage/login_page_view.dart
attendance/lib/loginPage/login_page_viewmodel.dart
attendance/lib/offline_page/offline_page.dart
attendance/lib/offline_page/offline_page_view.dart
attendance/lib/offline_page/offline_page_viewmodel.dart
attendance/lib/scan_exceptions.dart

#80 #84 code refactoring

---

attendance/lib/homePage/home_page_viewmodel.dart

#49 removed scanned validation

---

attendance/lib/AttendanceDatailsPage/attendance_details_page_view.dart
attendance/lib/AttendanceDatailsPage/attendance_details_page_viewmodel.dart
attendance/lib/backend/api.dart
attendance/lib/backend/attendance.dart
attendance/lib/backend/scan.dart
attendance/lib/backend/session.dart
attendance/lib/backend/user.dart
attendance/lib/db/database.dart
attendance/lib/homePage/home_page_view.dart
attendance/lib/homePage/home_page_viewmodel.dart
attendance/lib/loginPage/login_page_viewmodel.dart
attendance/lib/main.dart
attendance/test/api_test.dart
attendance/test/attendance_test.dart

PR for #102, #50 
refactoring to get rid of firebase database and some of its logic in the code.

#102 refactored user class
